Repository tauri-apps/tauri, pull requests merged in 2020-02, with the labels that each got.

#378 Feature: Tests in Core
  tauri/src/config.rs
  tauri/src/file_system.rs
  tauri/test/fixture/test.txt
Labels: chore, documentation, enhancement

#394 Bug(core): fix tests
  tauri/src/file_system.rs
Labels: bug, chore

#396 change serde versions to 1.0
  cli/tauri.js/templates/src-tauri/Cargo.toml
Labels: bug, chore

#398 refactor(tauri.js): Fix ESLint errors
  cli/tauri.js/.eslintrc.js
  cli/tauri.js/src/api/build.ts
  cli/tauri.js/src/api/dev.ts
  cli/tauri.js/src/api/info.ts
  cli/tauri.js/src/api/tauricon.ts
  cli/tauri.js/src/helpers/logger.ts
  cli/tauri.js/src/helpers/spawn.ts
  cli/tauri.js/src/helpers/tauri-config.ts
  cli/tauri.js/src/template/index.ts
  cli/tauri.js/src/types/config.ts
Labels: chore

#397 Refactor(All): Update and Format Deps for 2018
  cli/tauri-bundler/Cargo.toml
  cli/tauri-bundler/src/bundle.rs
  cli/tauri-bundler/src/bundle/category.rs
  cli/tauri-bundler/src/bundle/common.rs
  cli/tauri-bundler/src/bundle/deb_bundle.rs
  cli/tauri-bundler/src/bundle/ios_bundle.rs
  cli/tauri-bundler/src/bundle/msi_bundle.rs
  cli/tauri-bundler/src/bundle/osx_bundle.rs
  cli/tauri-bundler/src/bundle/rpm_bundle.rs
  cli/tauri-bundler/src/bundle/settings.rs
  cli/tauri-bundler/src/bundle/wix.rs
  cli/tauri-bundler/src/main.rs
  cli/tauri.js/templates/src-tauri/Cargo.toml
  cli/tauri.js/templates/src-tauri/src/cmd.rs
  cli/tauri.js/templates/src-tauri/src/main.rs
  examples/react/create-react-app/src-tauri/Cargo.toml
  examples/react/create-react-app/src-tauri/src/cmd.rs
  examples/react/create-react-app/src-tauri/src/main.rs
  examples/react/gatsby-themed-site/src-tauri/Cargo.toml
  examples/react/gatsby-themed-site/src-tauri/src/cmd.rs
  examples/react/gatsby-themed-site/src-tauri/src/main.rs
  examples/react/next.js/src-tauri/Cargo.toml
  examples/react/next.js/src-tauri/src/cmd.rs
  examples/react/next.js/src-tauri/src/main.rs
  examples/svelte/svelte-app/src-tauri/Cargo.toml
  examples/svelte/svelte-app/src-tauri/src/cmd.rs
  examples/svelte/svelte-app/src-tauri/src/main.rs
  examples/vanillajs/monolith/src-tauri/Cargo.toml
  examples/vanillajs/monolith/src-tauri/src/cmd.rs
  examples/vanillajs/monolith/src-tauri/src/main.rs
  examples/vue/nuxt-app/src-tauri/Cargo.toml
  examples/vue/nuxt-app/src-tauri/src/cmd.rs
  examples/vue/nuxt-app/src-tauri/src/main.rs
  examples/vue/quasar-app/src-tauri/Cargo.toml
  examples/vue/quasar-app/src-tauri/src/cmd.rs
  examples/vue/quasar-app/src-tauri/src/main.rs
  examples/vue/vue-cli-app/src-tauri/Cargo.toml
  examples/vue/vue-cli-app/src-tauri/src/cmd.rs
  examples/vue/vue-cli-app/src-tauri/src/main.rs
  tauri-api/src/dir.rs
  tauri-api/src/file.rs
  tauri-api/src/file/extract.rs
  tauri-api/src/lib.rs
  tauri-api/src/rpc.rs
  tauri-updater/src/lib.rs
  tauri-updater/src/updater.rs
  tauri/Cargo.toml
  tauri/build.rs
  tauri/src/config.rs
  tauri/src/endpoints/cmd.rs
  tauri/src/event.rs
  tauri/src/lib.rs
  tauri/src/salt.rs
  tauri/src/tcp.rs
Labels: chore, enhancement

#399 feat(workflow): publishing pipeline
  .github/workflows/cargo-publish.yml
  .github/workflows/npm-publish.yml
  .github/workflows/pr-to-master.yml
  .github/workflows/push-to-dev.yml
  .github/workflows/release-cargo.yml
  .github/workflows/release-npm.yml
Labels: enhancement

#426 Bug(Bundler): fix target arch in wix
  .github/workflows/smoke-tests-source.yml
  cli/tauri-bundler/src/bundle/wix.rs
Labels: bug, chore

#432 chore(workflow): update tangle release for more logging
  .github/workflows/release-cargo.yml
  .github/workflows/release-npm.yml
Labels: chore

#428 chore(workflows): split up prepare into postinstall and prepublishOnly
  cli/tauri.js/package.json
Labels: chore

#434 fix error file name 'tauri.conf.js' to 'tauri.conf.json'
  cli/tauri.js/src/runner.ts
Labels: bug

#470 fix(bundler) throw error when resource, external bin or icon not found
  cli/tauri-bundler/src/bundle/deb_bundle.rs
  cli/tauri-bundler/src/bundle/settings.rs
Labels: bug

#469 feature(tauri-bundler): add start menu shortcut on windows
  cli/tauri-bundler/src/bundle/templates/main.wxs
Labels: enhancement
