Repository tauri-apps/tauri, pull requests merged in 2020-01, with the labels that each got.

#259 Refactor(runner.rs) Clean up code to make it more composable and testable.
  tauri/src/app.rs
  tauri/src/app/runner.rs
  tauri/src/config.rs
  tauri/src/endpoints.rs
  tauri/src/lib.rs
Labels: documentation, enhancement

#281 feat(core) add testing and refactor
  tauri/src/app/runner.rs
  tauri/src/endpoints.rs
  tauri/src/lib.rs
  tauri/test/fixture/src-tauri/tauri.js
Labels: chore, documentation, enhancement

#284 Feat(core) rebuild on dist dir change fix: #285
  tauri/build.rs
Labels: bug, enhancement

#283 fix(bundler): Fix DMG script
  cli/tauri-cli/src/bundle/dmg_bundle.rs
  cli/tauri-cli/src/bundle/settings.rs
  cli/tauri-cli/src/bundle/templates/bundle_dmg
Labels: bug

#282 only enable renovate for certain folders
  renovate.json
Labels: chore

#260 feat(examples): add vue cli app example
  examples/vue/vue-cli-app/.gitignore
  examples/vue/vue-cli-app/README.md
  examples/vue/vue-cli-app/babel.config.js
  examples/vue/vue-cli-app/package.json
  examples/vue/vue-cli-app/public/favicon.ico
  examples/vue/vue-cli-app/public/index.html
  examples/vue/vue-cli-app/src-tauri/.gitignore
  examples/vue/vue-cli-app/src-tauri/Cargo.toml
  examples/vue/vue-cli-app/src-tauri/icons/128x128.png
  examples/vue/vue-cli-app/src-tauri/icons/128x128@2x.png
  examples/vue/vue-cli-app/src-tauri/icons/32x32.png
  examples/vue/vue-cli-app/src-tauri/icons/Square107x107Logo.png
  examples/vue/vue-cli-app/src-tauri/icons/Square142x142Logo.png
  examples/vue/vue-cli-app/src-tauri/icons/Square150x150Logo.png
  examples/vue/vue-cli-app/src-tauri/icons/Square284x284Logo.png
  examples/vue/vue-cli-app/src-tauri/icons/Square30x30Logo.png
  examples/vue/vue-cli-app/src-tauri/icons/Square310x310Logo.png
  examples/vue/vue-cli-app/src-tauri/icons/Square44x44Logo.png
  examples/vue/vue-cli-app/src-tauri/icons/Square71x71Logo.png
  examples/vue/vue-cli-app/src-tauri/icons/Square89x89Logo.png
  examples/vue/vue-cli-app/src-tauri/icons/StoreLogo.png
  examples/vue/vue-cli-app/src-tauri/icons/icon.icns
  examples/vue/vue-cli-app/src-tauri/icons/icon.ico
  examples/vue/vue-cli-app/src-tauri/icons/icon.png
  examples/vue/vue-cli-app/src-tauri/rustfmt.toml
  examples/vue/vue-cli-app/src-tauri/src/build.rs
  examples/vue/vue-cli-app/src-tauri/src/cmd.rs
  examples/vue/vue-cli-app/src-tauri/src/main.rs
  examples/vue/vue-cli-app/src-tauri/tauri.conf.json
  examples/vue/vue-cli-app/src/App.vue
  examples/vue/vue-cli-app/src/assets/logo.png
  examples/vue/vue-cli-app/src/components/HelloWorld.vue
  examples/vue/vue-cli-app/src/main.js
  examples/vue/vue-cli-app/yarn.lock
Labels: chore

#300 fix(examples): fix breaking change upstream
  examples/react/gatsby-themed-site/gatsby-config.js
Labels: chore

#302 chore(renovate): top level disable completely turns it off
  renovate.json
Labels: chore

#303 Chore(examples) update cargo.toml with appropriate dependencies.
  examples/react/create-react-app/src-tauri/Cargo.toml
  examples/react/gatsby-themed-site/src-tauri/Cargo.toml
  examples/react/next.js/src-tauri/Cargo.toml
  examples/svelte/svelte-app/src-tauri/Cargo.toml
  examples/vanillajs/monolith/src-tauri/Cargo.toml
  examples/vue/quasar-app/src-tauri/Cargo.toml
  examples/vue/vue-cli-app/src-tauri/Cargo.toml
Labels: chore

#310 Feat(CLI) Icon Check fix: #309
  cli/tauri-cli/src/bundle.rs
  cli/tauri-cli/src/main.rs
  cli/tauri.js/templates/src-tauri/src/build.rs
Labels: bug, enhancement

#308 Bump actions/checkout from v1 to v2
  .github/workflows/cargo-publish.yml
  .github/workflows/npm-publish.yml
  .github/workflows/smoke-test-prod.yml
  .github/workflows/smoke-tests-source.yml
  .github/workflows/test-on-pr.yml
Labels: chore

#311 Refact(api) Add error chain to Tauri_api.
  .github/workflows/test-on-pr.yml
  tauri-api/Cargo.toml
  tauri-api/src/command.rs
  tauri-api/src/dir.rs
  tauri-api/src/file.rs
  tauri-api/src/file/error.rs
  tauri-api/src/file/extract.rs
  tauri-api/src/file/file_move.rs
  tauri-api/src/lib.rs
  tauri-api/src/version.rs
  tauri-api/src/version/error.rs
  tauri-api/test/test.txt
  tauri-api/test/test_binary
  tauri-updater/src/updater/error.rs
  tauri/src/file_system.rs
Labels: chore, documentation, enhancement

#326 feat(workflows): first-timer message
  .github/workflows/greetings.yml
Labels: enhancement

#332 refactor(Bundler, API) clean up external binary logic
  cli/tauri-cli/Cargo.toml
  cli/tauri-cli/src/bundle.rs
  cli/tauri-cli/src/bundle/deb_bundle.rs
  cli/tauri-cli/src/bundle/osx_bundle.rs
  cli/tauri-cli/src/bundle/settings.rs
  cli/tauri-cli/src/bundle/wix.rs
  cli/tauri-cli/src/main.rs
  tauri-api/src/command.rs
  tauri-api/src/lib.rs
  tauri/src/lib.rs
Labels: chore, documentation, enhancement

#335 Refactor(Updater) Modernize Updater Crate and add Utils Crate
  Cargo.toml
  cli/tauri-cli/Cargo.toml
  cli/tauri-cli/src/bundle/settings.rs
  cli/tauri-cli/src/main.rs
  cli/tauri-cli/src/platform.rs
  tauri-api/Cargo.toml
  tauri-api/src/command.rs
  tauri-api/src/lib.rs
  tauri-updater/Cargo.toml
  tauri-updater/src/http.rs
  tauri-updater/src/http/error.rs
  tauri-updater/src/http/link_value.rs
  tauri-updater/src/lib.rs
  tauri-updater/src/macros.rs
  tauri-updater/src/platform.rs
  tauri-updater/src/platform/error.rs
  tauri-updater/src/updater.rs
  tauri-updater/src/updater/error.rs
  tauri-updater/src/updater/github.rs
  tauri-updater/src/updater/github/release.rs
  tauri-utils/Cargo.toml
  tauri-utils/src/lib.rs
  tauri-utils/src/platform.rs
  tauri-utils/src/process.rs
  tauri/Cargo.toml
Labels: bug, chore, documentation, enhancement

#338 fix greeting message extra characters
  .github/workflows/greetings.yml
Labels: chore

#306 chore(examples) add nuxt example
  cli/tauri.js/templates/tauri.js
  examples/vue/nuxt-app/.editorconfig
  examples/vue/nuxt-app/.gitignore
  examples/vue/nuxt-app/README.md
  examples/vue/nuxt-app/assets/README.md
  examples/vue/nuxt-app/components/Logo.vue
  examples/vue/nuxt-app/components/README.md
  examples/vue/nuxt-app/layouts/README.md
  examples/vue/nuxt-app/layouts/default.vue
  examples/vue/nuxt-app/middleware/README.md
  examples/vue/nuxt-app/middleware/tauri.js
  examples/vue/nuxt-app/nuxt.config.js
  examples/vue/nuxt-app/package.json
  examples/vue/nuxt-app/pages/README.md
  examples/vue/nuxt-app/pages/index.vue
  examples/vue/nuxt-app/plugins/README.md
  examples/vue/nuxt-app/src-tauri/.gitignore
  examples/vue/nuxt-app/src-tauri/Cargo.toml
  examples/vue/nuxt-app/src-tauri/icons/128x128.png
  examples/vue/nuxt-app/src-tauri/icons/128x128@2x.png
  examples/vue/nuxt-app/src-tauri/icons/32x32.png
  examples/vue/nuxt-app/src-tauri/icons/Square107x107Logo.png
  examples/vue/nuxt-app/src-tauri/icons/Square142x142Logo.png
  examples/vue/nuxt-app/src-tauri/icons/Square150x150Logo.png
  examples/vue/nuxt-app/src-tauri/icons/Square284x284Logo.png
  examples/vue/nuxt-app/src-tauri/icons/Square30x30Logo.png
  examples/vue/nuxt-app/src-tauri/icons/Square310x310Logo.png
  examples/vue/nuxt-app/src-tauri/icons/Square44x44Logo.png
  examples/vue/nuxt-app/src-tauri/icons/Square71x71Logo.png
  examples/vue/nuxt-app/src-tauri/icons/Square89x89Logo.png
  examples/vue/nuxt-app/src-tauri/icons/StoreLogo.png
  examples/vue/nuxt-app/src-tauri/icons/icon.icns
  examples/vue/nuxt-app/src-tauri/icons/icon.ico
  examples/vue/nuxt-app/src-tauri/icons/icon.png
  examples/vue/nuxt-app/src-tauri/rustfmt.toml
  examples/vue/nuxt-app/src-tauri/src/build.rs
  examples/vue/nuxt-app/src-tauri/src/cmd.rs
  examples/vue/nuxt-app/src-tauri/src/main.rs
  examples/vue/nuxt-app/src-tauri/tauri.conf.json
  examples/vue/nuxt-app/static/README.md
  examples/vue/nuxt-app/static/favicon.ico
  examples/vue/nuxt-app/store/README.md
  examples/vue/nuxt-app/yarn.lock
Labels: chore

#376 Refactor(Core) add error chain
  tauri/Cargo.toml
  tauri/src/app/runner.rs
  tauri/src/config.rs
  tauri/src/endpoints.rs
  tauri/src/file_system.rs
  tauri/src/lib.rs
Labels: bug, chore, documentation, enhancement
