Repository tauri-apps/tauri, pull requests merged in 2020-03, with the labels that each got.

#468 Refact(All): (WIP) Cleanup workflow and add Windows Features.
  cli/tauri-bundler/src/bundle/settings.rs
  cli/tauri-bundler/src/bundle/templates/main.wxs
  cli/tauri-bundler/src/main.rs
  tauri-api/src/command.rs
  tauri/build.rs
  tauri/src/endpoints.rs
  tauri/src/lib.rs
Labels: bug, chore, documentation, enhancement

#477 chore(workflow): tauri-bundler path considering workspace
  .github/workflows/release-cargo.yml
Labels: bug, chore

#479 fix(template) incorrect package > authors field on Cargo.toml
  cli/tauri.js/templates/src-tauri/Cargo.toml
Labels: bug

#474 fix(tauri) do not use template literals and fix entry for IE
  cli/tauri.js/templates/tauri.js
  tauri/src/app/runner.rs
  tauri/src/endpoints.rs
  tauri/src/lib.rs
Labels: bug

#480 feat(Bundler) Add Update, UI and Custom Install Dir
  cli/tauri-bundler/src/bundle/templates/main.wxs
  cli/tauri-bundler/src/bundle/wix.rs
Labels: chore, enhancement

#487 Chore(Tauri): fix docs.rs
  tauri/Cargo.toml
Labels: chore, documentation

#492 fix(bundler) do not require [package.metadata.bundle] for tauri projects
  cli/tauri-bundler/src/bundle/settings.rs
Labels: bug

#244 feat(tests) add e2e test
  .github/workflows/test-on-pr.yml
  cli/tauri.js/.gitignore
  cli/tauri.js/babel.config.js
  cli/tauri.js/jest.config.js
  cli/tauri.js/package.json
  cli/tauri.js/src/api/build.ts
  cli/tauri.js/src/api/dev.ts
  cli/tauri.js/src/api/info.ts
  cli/tauri.js/src/api/tauricon.ts
  cli/tauri.js/src/helpers/non-webpack-require.ts
  cli/tauri.js/src/helpers/spawn.ts
  cli/tauri.js/src/helpers/tauri-config.ts
  cli/tauri.js/src/runner.ts
  cli/tauri.js/test/jest/__tests__/build.spec.js
  cli/tauri.js/test/jest/__tests__/dev.spec.js
  cli/tauri.js/test/jest/__tests__/tauri.spec.js
  cli/tauri.js/test/jest/fixtures/app-test-setup.js
  cli/tauri.js/test/jest/fixtures/app/.gitignore
  cli/tauri.js/test/jest/fixtures/app/dist/index.html
  cli/tauri.js/test/jest/fixtures/app/index.js
  cli/tauri.js/test/jest/fixtures/app/package.json
  cli/tauri.js/test/jest/fixtures/app/src-tauri/.gitignore
  cli/tauri.js/test/jest/fixtures/app/src-tauri/Cargo.toml
  cli/tauri.js/test/jest/fixtures/app/src-tauri/icons/128x128.png
  cli/tauri.js/test/jest/fixtures/app/src-tauri/icons/128x128@2x.png
  cli/tauri.js/test/jest/fixtures/app/src-tauri/icons/32x32.png
  cli/tauri.js/test/jest/fixtures/app/src-tauri/icons/Square107x107Logo.png
  cli/tauri.js/test/jest/fixtures/app/src-tauri/icons/Square142x142Logo.png
  cli/tauri.js/test/jest/fixtures/app/src-tauri/icons/Square150x150Logo.png
  cli/tauri.js/test/jest/fixtures/app/src-tauri/icons/Square284x284Logo.png
  cli/tauri.js/test/jest/fixtures/app/src-tauri/icons/Square30x30Logo.png
  cli/tauri.js/test/jest/fixtures/app/src-tauri/icons/Square310x310Logo.png
  cli/tauri.js/test/jest/fixtures/app/src-tauri/icons/Square44x44Logo.png
  cli/tauri.js/test/jest/fixtures/app/src-tauri/icons/Square71x71Logo.png
  cli/tauri.js/test/jest/fixtures/app/src-tauri/icons/Square89x89Logo.png
  cli/tauri.js/test/jest/fixtures/app/src-tauri/icons/StoreLogo.png
  cli/tauri.js/test/jest/fixtures/app/src-tauri/icons/icon.icns
  cli/tauri.js/test/jest/fixtures/app/src-tauri/icons/icon.ico
  cli/tauri.js/test/jest/fixtures/app/src-tauri/icons/icon.png
  cli/tauri.js/test/jest/fixtures/app/src-tauri/rustfmt.toml
  cli/tauri.js/test/jest/fixtures/app/src-tauri/src/cmd.rs
  cli/tauri.js/test/jest/fixtures/app/src-tauri/src/main.rs
  cli/tauri.js/test/jest/fixtures/app/src-tauri/tauri.conf.json
  cli/tauri.js/test/jest/fixtures/app/yarn.lock
  cli/tauri.js/test/jest/raw-loader-transformer.js
  cli/tauri.js/webpack.config.js
  cli/tauri.js/yarn.lock
Labels: chore

#497 feat(tauri.js) keep running on failures & watch tauri lib on contribs
  cli/tauri.js/bin/tauri-dev.js
  cli/tauri.js/src/runner.ts
  cli/tauri.js/src/types/config.ts
Labels: enhancement

#499 feat(core) add cargo examples
  .scripts/init_env.bat
  .scripts/init_env.ps1
  .scripts/init_env.sh
  tauri/Cargo.toml
  tauri/examples/communication/dist/index.html
  tauri/examples/communication/dist/index.tauri.html
  tauri/examples/communication/package.json
  tauri/examples/communication/src-tauri/.gitignore
  tauri/examples/communication/src-tauri/Cargo.toml
  tauri/examples/communication/src-tauri/icons/128x128.png
  tauri/examples/communication/src-tauri/icons/128x128@2x.png
  tauri/examples/communication/src-tauri/icons/32x32.png
  tauri/examples/communication/src-tauri/icons/Square107x107Logo.png
  tauri/examples/communication/src-tauri/icons/Square142x142Logo.png
  tauri/examples/communication/src-tauri/icons/Square150x150Logo.png
  tauri/examples/communication/src-tauri/icons/Square284x284Logo.png
  tauri/examples/communication/src-tauri/icons/Square30x30Logo.png
  tauri/examples/communication/src-tauri/icons/Square310x310Logo.png
  tauri/examples/communication/src-tauri/icons/Square44x44Logo.png
  tauri/examples/communication/src-tauri/icons/Square71x71Logo.png
  tauri/examples/communication/src-tauri/icons/Square89x89Logo.png
  tauri/examples/communication/src-tauri/icons/StoreLogo.png
  tauri/examples/communication/src-tauri/icons/icon.icns
  tauri/examples/communication/src-tauri/icons/icon.ico
  tauri/examples/communication/src-tauri/icons/icon.png
  tauri/examples/communication/src-tauri/rustfmt.toml
  tauri/examples/communication/src-tauri/src/build.rs
  tauri/examples/communication/src-tauri/src/cmd.rs
  tauri/examples/communication/src-tauri/src/main.rs
  tauri/examples/communication/src-tauri/tauri.conf.json
  tauri/src/lib.rs
  tauri/src/view.rs
Labels: chore, documentation, enhancement

#502 feat(bundler) bail if can't parse tauri config
  cli/tauri-bundler/src/bundle/settings.rs
Labels: enhancement

#495 feat(tauri.js) improve api module with type defs for each API function
  cli/tauri.js/api/event.js
  cli/tauri.js/api/fs.js
  cli/tauri.js/api/index.js
  cli/tauri.js/api/process.js
  cli/tauri.js/api/tauri.js
  cli/tauri.js/api/window.js
  cli/tauri.js/src/runner.ts
  cli/tauri.js/templates/src-tauri/src/main.rs
  cli/tauri.js/templates/tauri.js
  tauri-api/Cargo.toml
  tauri-api/src/lib.rs
  tauri-api/src/tcp.rs
  tauri/Cargo.toml
  tauri/examples/communication/src-tauri/src/main.rs
  tauri/src/app.rs
  tauri/src/app/runner.rs
  tauri/src/endpoints.rs
  tauri/src/endpoints/cmd.rs
  tauri/src/endpoints/file_system.rs
  tauri/src/endpoints/salt.rs
  tauri/src/event.rs
  tauri/src/lib.rs
  tauri/src/salt.rs
  tauri/src/view.rs
Labels: enhancement

#493 fix(tauri.js) determine app path correctly
  .github/workflows/test-on-pr.yml
  cli/tauri.js/jest.config.js
  cli/tauri.js/src/api/info.ts
  cli/tauri.js/src/api/tauricon.ts
  cli/tauri.js/src/entry.ts
  cli/tauri.js/src/helpers/app-paths.ts
  cli/tauri.js/src/runner.ts
  cli/tauri.js/src/template/index.ts
  cli/tauri.js/test/jest/__tests__/tauri.spec.js
  cli/tauri.js/test/jest/__tests__/tauricon.spec.js
  cli/tauri.js/test/jest/__tests__/template.spec.js
  cli/tauri.js/test/jest/fixtures/app-test-setup.js
  cli/tauri.js/webpack.config.js
  tauri/src/endpoints/file_system.rs
Labels: bug

#514 feat(tauri) add dialog API
  cli/tauri.js/api/dialog.js
  cli/tauri.js/templates/tauri.js
  tauri-api/Cargo.toml
  tauri-api/src/dialog.rs
  tauri-api/src/lib.rs
  tauri/Cargo.toml
  tauri/examples/communication/dist/dialog.js
  tauri/examples/communication/dist/index.html
  tauri/examples/communication/dist/index.tauri.html
  tauri/src/endpoints.rs
  tauri/src/endpoints/cmd.rs
  tauri/src/endpoints/dialog.rs
  tauri/src/lib.rs
Labels: enhancement

#512 feat(tauri) extend file system API
  cli/tauri.js/api/fs.js
  cli/tauri.js/templates/tauri.js
  tauri-api/src/dir.rs
  tauri/Cargo.toml
  tauri/examples/communication/dist/index.tauri.html
  tauri/src/endpoints.rs
  tauri/src/endpoints/cmd.rs
  tauri/src/endpoints/file_system.rs
  tauri/src/lib.rs
Labels: enhancement

#528 Chore(release): [version updates] update to core, updater, utils, api and bundler
  cli/tauri-bundler/Cargo.toml
  tauri-api/Cargo.toml
  tauri-updater/Cargo.toml
  tauri-utils/Cargo.toml
  tauri/Cargo.toml
Labels: chore
