Repository tauri-apps/tauri, pull requests merged in 2023-07, with the labels that each got.

#7386 fix(bundler/nsis): fix installer incorrect copyright info
  .changes/fix-nsis-legal-copyright.md
  tooling/bundler/src/bundle/windows/templates/installer.nsi
Labels: status: needs review

#7394 feat(api/http): properly handle Files in Body.form, closes #7390
  .changes/api-formAsync.md
  core/tauri/scripts/bundle.global.js
  examples/api/dist/assets/index.css
  examples/api/dist/assets/index.js
  examples/api/src-tauri/Cargo.lock
  tooling/api/docs/js-api.json
  tooling/api/src/http.ts
Labels: status: needs review

#3934 fix(cli): handle symlinks in updater bundler, closes #3933
  core/tauri/src/api/file/extract.rs
  core/tests/app-updater/frameworks/test.framework/Headers
  core/tests/app-updater/frameworks/test.framework/Resources
  core/tests/app-updater/frameworks/test.framework/Versions/A/Headers/test.h
  core/tests/app-updater/frameworks/test.framework/Versions/A/Resources/Info.plist
  core/tests/app-updater/frameworks/test.framework/Versions/A/Resources/LICENSE
  core/tests/app-updater/frameworks/test.framework/Versions/A/test
  core/tests/app-updater/frameworks/test.framework/Versions/Current
  core/tests/app-updater/frameworks/test.framework/test
  core/tests/app-updater/tauri.conf.json
  core/tests/app-updater/tests/update.rs
  tooling/bundler/src/bundle/updater_bundle.rs
Labels: security: reviewed

#5950 feat: allow specifying a resource map, closes #5844
  .changes/resources-map-bundler.md
  .changes/resources-map.md
  core/tauri-build/src/lib.rs
  core/tauri-config-schema/schema.json
  core/tauri-runtime-wry/src/lib.rs
  core/tauri-utils/src/config.rs
  core/tauri-utils/src/resources.rs
  examples/resources/src-tauri/Cargo.lock
  examples/resources/src-tauri/Cargo.toml
  tooling/bundler/src/bundle/settings.rs
  tooling/bundler/src/bundle/windows/msi/wix.rs
  tooling/bundler/src/bundle/windows/nsis.rs
  tooling/cli/schema.json
  tooling/cli/src/interface/rust.rs
Labels: security: needs audit

#7437 feat: add visible_on_all_workspaces, closes #6589
  .changes/add-visible-on-all-workspaces.md
  core/tauri-config-schema/schema.json
  core/tauri-runtime-wry/src/lib.rs
  core/tauri-runtime/src/lib.rs
  core/tauri-runtime/src/webview.rs
  core/tauri-utils/src/config.rs
  core/tauri/src/test/mock_runtime.rs
  core/tauri/src/window.rs
  tooling/api/docs/js-api.json
  tooling/cli/schema.json
Labels: status: needs review
