Repository tauri-apps/tauri, pull requests merged in 2023-05, with the labels that each got.

#7023 feat(cli): `plugin add` command
  .changes/add-command.md
  tooling/cli/src/helpers/mod.rs
  tooling/cli/src/helpers/npm.rs
  tooling/cli/src/info/env_nodejs.rs
  tooling/cli/src/info/mod.rs
  tooling/cli/src/info/packages_nodejs.rs
  tooling/cli/src/plugin.rs
  tooling/cli/src/plugin/add.rs
Labels: status: needs review

#7026 feat: current_version feature
  .changes/add-webview-version.md
  core/tauri-runtime-wry/src/lib.rs
  core/tauri/src/lib.rs
Labels: status: needs review

#6933 feat(bundler/NSIS): uninstall previous wix if exist, closes #6859
  .changes/nsis-uninstall-wix.md
  tooling/bundler/src/bundle/windows/templates/installer.nsi
Labels: status: needs review

#6998 feat(nsis): implement `passive` mode, closes #6955
  .changes/nsis-downgrades.md
  .changes/nsis-passive-mode.md
  .changes/nsis-restart-flag.md
  .changes/nsis-silent-kill.md
  .changes/nsis-silent-shortcuts.md
  core/tauri-config-schema/schema.json
  core/tauri-utils/src/config.rs
  core/tauri/src/updater/core.rs
  tooling/bundler/src/bundle/windows/templates/installer.nsi
  tooling/cli/Cargo.lock
  tooling/cli/schema.json
Labels: status: needs review

#5180 feat(bundler): custom desktop file template, closes #5176
  .changes/deb-custom-desktop-file-config.md
  .changes/deb-custom-desktop-file.md
  core/tauri-config-schema/schema.json
  core/tauri-utils/src/config.rs
  tooling/bundler/src/bundle/linux/debian.rs
  tooling/bundler/src/bundle/linux/templates/main.desktop
  tooling/bundler/src/bundle/settings.rs
  tooling/cli/schema.json
  tooling/cli/src/interface/rust.rs
Labels: platform: Linux, scope: bundler

#7057 fix(bundler/nsis): calculate accurate app size, closes #7056
  .changes/nsis-accurate-app-size.md
  tooling/bundler/src/bundle/windows/templates/installer.nsi
Labels: security: needs feedback
